apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
spec:
  ports:
    - port: 9092
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-api
spec:
  type: LoadBalancer
  ports:
  - port: 19092
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: broker
        image: confluentinc/cp-kafka
        ports:
        - containerPort: 9092
        env:
        # server broker configurations
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_NUM_PARTITIONS
          value: "3"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
          
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-broker:9092,CONNECTIONS_FROM_HOST://localhost:19092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT"
            
        # zookeeper settings
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-ip-service:2181"
            
        volumeMounts:
        - name: root-volume
          mountPath: /etc/kafka
          
      volumes:
      - name: root-volume
        emptyDir: {}
