apiVersion: v1
kind: Service
metadata:
  name: phobos-web-consumer-api
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '80'
  labels:
    app: domain-customers
spec:
  type: LoadBalancer
  ports:
    - name: query-http
      port: 2880
      protocol: TCP
      targetPort: 80
  selector:
    app: phobos-web-consumer
---
apiVersion: v1
kind: Service
metadata:
  name: phobos-web-consumer
  labels:
    app: phobos-web-consumer
spec:
  clusterIP: None
  ports:
  - name: remoting
    port: 4055
    targetPort: 4055
  selector:
    app: phobos-web-consumer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: phobos-web-consumer
  labels:
    app: phobos-web-consumer
spec:
  serviceName: "phobos-web-consumer"
  replicas: 3
  selector:
    matchLabels:
      app: phobos-web-consumer
  template:
    metadata:
      labels:
        app: phobos-web-consumer
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: phobos-web-consumer
        image: petabridge.phobos.kafka.consumer:0.1.3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "pbm 127.0.0.1:9110 cluster leave"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_SEEDS
          value: akka.tcp://ClusterKafkaSys@phobos-web-consumer-0.phobos-web-consumer:4055,akka.tcp://ClusterKafkaSys@phobos-web-consumer-1.phobos-web-consumer:4055,akka.tcp://ClusterKafkaSys@phobos-web-consumer-2.phobos-web-consumer:4055
        - name: CLUSTER_IP
          value: "$(POD_NAME).phobos-web-consumer"
        - name: CLUSTER_PORT
          value: "4055"              
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: pb-configs
              key: environment
        - name: KAFKA_SERVICE_HOST
          value: "kafka-broker"
        - name: KAFKA_SERVICE_PORT
          value: "9092"
        - name: JAEGER_AGENT_HOST
          value: "jaeger-agent"
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: SEQ_SERVICE_HOST 
          value: "seq"
        - name: SEQ_SERVICE_PORT
          value: "8988"
        livenessProbe:
          tcpSocket:
            port: 4055
        readinessProbe:
          httpGet:
            path: "/ready"
            port: 80
        ports:
        - containerPort: 4055
          protocol: TCP
        - containerPort: 80
          protocol: TCP